[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Transportation Infrastructure: Exploring the Role of Intelligent Technologies in Designing Smart Cities"
